version: "3.8"

services:
    web:
        image: bee-website-php-image
        build:
            context: ..
            dockerfile: Docker/Dockerfile
        container_name: bee-website-php-container
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www/html
        environment:
            DB_HOST: db
            DB_NAME: the_bee_website_db
            DB_USER: root
            DB_PASSWORD: Abcd@1234
        depends_on:
            - db

    db:
        image: bee-website-mysql-image
        build:
            context: .
            dockerfile_inline: FROM mysql:8.0
        restart: always
        container_name: bee-website-mysql-container

        environment:
            MYSQL_ROOT_PASSWORD: Abcd@1234
            MYSQL_DATABASE: bee_website_db
        ports:
            - "3306:3306"
        volumes:
            - ../SQL/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
